"""empty message

Revision ID: 049f6f5788aa
Revises: 
Create Date: 2018-03-25 20:30:38.836347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049f6f5788aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweetID', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_time'), 'user', ['time'], unique=False)
    op.create_index(op.f('ix_user_tweetID'), 'user', ['tweetID'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tweetID'), table_name='user')
    op.drop_index(op.f('ix_user_time'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
