"""trending table

Revision ID: 2db2c36ffb74
Revises: 38bb334c8592
Create Date: 2018-03-30 15:02:08.719503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db2c36ffb74'
down_revision = '38bb334c8592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trending',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashtag', sa.String(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trending_hashtag'), 'trending', ['hashtag'], unique=True)
    op.create_index(op.f('ix_trending_time'), 'trending', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trending_time'), table_name='trending')
    op.drop_index(op.f('ix_trending_hashtag'), table_name='trending')
    op.drop_table('trending')
    # ### end Alembic commands ###
