"""empty message

Revision ID: 38bb334c8592
Revises: 049f6f5788aa
Create Date: 2018-03-25 20:59:41.582762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38bb334c8592'
down_revision = '049f6f5788aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweetID', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tweet_time'), 'tweet', ['time'], unique=False)
    op.create_index(op.f('ix_tweet_tweetID'), 'tweet', ['tweetID'], unique=True)
    op.drop_index('ix_user_time', table_name='user')
    op.drop_index('ix_user_tweetID', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tweetID', sa.INTEGER(), nullable=True),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_tweetID', 'user', ['tweetID'], unique=1)
    op.create_index('ix_user_time', 'user', ['time'], unique=False)
    op.drop_index(op.f('ix_tweet_tweetID'), table_name='tweet')
    op.drop_index(op.f('ix_tweet_time'), table_name='tweet')
    op.drop_table('tweet')
    # ### end Alembic commands ###
